# .github/workflows/sync-draw-io.yml
name: Sync draw-io Libraries

on:
  schedule:
    # Synct jede Stunde um Minute 0
    - cron: '0 * * * *'
  # Manuelles Triggern über GitHub UI
  workflow_dispatch: {}

jobs:
  sync-draw-io:
    runs-on: ubuntu-latest

    steps:
      # 1. Ziel-Repo auschecken
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Quell-Repo auschecken
      - name: Checkout source repo (unifi)
        uses: actions/checkout@v4
        with:
          repository: WhiskeyTang0F0xtr0t/unifi
          path: source-unifi
          fetch-depth: 0

      # 3. draw-io-Unterordner kopieren
      - name: Sync draw-io folder
        run: |
          mkdir -p draw-io
          rsync -av --delete source-unifi/draw-io/ draw-io/

      # 4. Prüfen, ob es Änderungen gibt
      - name: Detect changes
        id: git-check
        run: |
          echo "::set-output name=changed::$(git status --porcelain)"

      # 5. Bei Änderungen: Pull Request erstellen
      - name: Create Pull Request
        if: steps.git-check.outputs.changed != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔄 Sync draw-io from unifi repo"
          branch: sync/draw-io
          title: "Sync draw-io aus WhiskeyTang0F0xtr0t/unifi"
          body: |
            Dieser Pull Request synchronisiert den aktuellen Stand von `draw-io`
            aus dem Repository `WhiskeyTang0F0xtr0t/unifi`.
          labels: sync, automation
