name: Sync draw-io folder from WhiskeyTang0F0xtr0t

on:
  workflow_dispatch:     # manuell auslösbar
  schedule:
    - cron: '0 0 * * *'   # täglich Mitternacht

jobs:
  sync-drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: |
          git clone --depth 1 https://github.com/WhiskeyTang0F0xtr0t/unifi.git temp/

      - name: Copy draw‑io folder
        run: |
          rm -rf external/unifi-drawio
          mkdir -p external
          cp -r temp/draw-io external/unifi-drawio
          rm -rf temp/

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add external/unifi-drawio
            git commit -m "Sync draw‑io from WhiskeyTang0F0xtr0t/unifi"
            git push
          else
            echo "No changes"
          fi
